BEGIN;

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CHANNEL_GROUP_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CHANNEL_GROUP_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CHANNEL_GROUP_ARCHIVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CHANNEL_GROUP_CHANNELS_REPLACED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'VIEWER_CHANNEL_GROUPS_REPLACED';

COMMIT;
